# Site Settings
title: Colton Fischer
url: 'https://coltonfischer.github.io'
baseurl: #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: # blue turquoise green berry orange ceramic


# Profile information
name: Colton Fischer
tagline: Software Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'A Software Developer that enhances and extends complex enterprise applications through 
modern web development practices.  Proficient in the production and consumption of APIs to create 
modular and tightly integrated web applications.  Experienced in a wide array of full stack 
technologies and is passionate about learning new skills.'

# Sidebar links
# email: 
# phone: 012 345 6789
website: coltonfischer.com #do not add http://
linkedin: coltonfischer
github: coltonfischer
twitter: '@colton_fischer'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
